set_hold_time:
  target:
    device:
      integration: lyric_t9
    entity:
      integration: lyric_t9
      domain: climate
  fields:
    time_period:
      default: "01:00:00"
      example: "01:00:00"
      required: true
      selector:
        text:
set_room_priority:
  target:
    device:
      integration: lyric_t9
    entity:
      integration: lyric_t9
      domain: climate
  fields:
    priority_type:
      default: "PickARoom"
      example: "PickARoom"
      required: true
      selector:
        select:
          options:
            - "PickARoom"
            - "WholeHouse"
            - "FollowMe"
    rooms:
      required: true
      selector:
        target:
          device:
            integration: lyric_t9
        